
-- Armazena processos de importação de dados TUST
  CREATE TABLE "RSM_TUSTPROCESSOIMPORTACAO" 
   (	"ID_PROCESSOIMPORTACAO" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "USUARIOALTERACAO" VARCHAR2(30),
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        CONSTRAINT "RSM_TUSTPROCESSOIMPORTACAO_PK" PRIMARY KEY ("ID_PROCESSOIMPORTACAO")    
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTPROCESSOIMPORTACAO" NOCACHE NOORDER NOCYCLE;


   
-- Armazena execuções automáticas de importação TUST
  CREATE TABLE "RSM_TUSTIMPAUTOMATICA" 
   (	"ID_IMPOAUTOMATICA" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "USUARIOALTERACAO" VARCHAR2(30),
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORPROCESSOIMPORTACAO" NUMBER,
        "HORAEXECUCAO" TIMESTAMP,
        "STATUS" VARCHAR2(20),
        "STATUSIMPORTACAO" VARCHAR2(20),
        "DATAULTIMAEXECUCAO" TIMESTAMP,
        "DATAFIMULTIMAEXECUCAO" TIMESTAMP,
        "DURACAOULTIMAEXECUCAO" VARCHAR2(20),
        CONSTRAINT "RSM_TUSTIMPAUTOMATICA_PK" PRIMARY KEY ("ID_IMPAUTOMATICA")
   );

   CREATE SEQUENCE "SEQ_RSM_TUSTIMPAUTOMATICA" NOCACHE NOORDER NOCYCLE;

-- Armazena execuções de importação automática TUST
  CREATE TABLE "RSM_TUSTIMPAUTEXECUCAO" 
   (	"ID_IMPAUTEXECUCAO" NUMBER NOT NULL, 
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORIMPORTACAOAUTOMATICA" NUMBER,
        "IDENTIFICADORIMPORTACAODESTINO" NUMBER,
        "DATAEXECUCAO" TIMESTAMP,
        "STATUS" VARCHAR2(30),
        "QTDERROS" NUMBER,
        "IDENTIFICADORPROCESSOIMPORTACAO" NUMBER,
        CONSTRAINT "RSM_TUSTIMPAUTEXECUCAO_PK" PRIMARY KEY ("ID_IMPAUTEXECUCAO")
   );

   CREATE SEQUENCE "SEQ_RSM_TUSTIMPAUTEXECUCAO" NOCACHE NOORDER NOCYCLE;


-- Armazena documentos importados automaticamente
   CREATE TABLE "RSM_TUSTIMPAUTDOCUMENTO" (
        "ID_IMPAUTDOCUMENTO" NUMBER NOT NULL,
        -- Campos de ImportacaoAutomaticaDocumento
        "IDENTIFICADOR_DOC" NUMBER,
        "IDENTIFICADORIMPORTACAOAUTOMATICA" NUMBER,
        "IDENTIFICADORIMPORTACAOAUTOMATICAEXECUCAO" NUMBER,
        "TIPODOCUMENTO" VARCHAR2(50),
        -- Campos de FaturaTransmissao
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORAVISODEBITOTRANSMISSAO" NUMBER,
        "IDENTIFICADORAVISODEBITOTRANSMISSAOITEM" NUMBER,
        "IDENTIFICADORTRANSMISSORA" NUMBER,
        "IDENTIFICADORFATURATRANSMISSAOPAI" NUMBER,
        "FORMAPAGAMENTO" VARCHAR2(30),
        "CODIGOTRANSMISSORAONS" VARCHAR2(10),
        "CODIGOEMPRESAONS" VARCHAR2(10),
        "CODIGOEMPRESA" VARCHAR2(10),
        "CODIGOFILIAL" VARCHAR2(10),
        "DATACOMPETENCIA" TIMESTAMP,
        "CODIGOFATURA" VARCHAR2(20),
        "DATAFATURA" TIMESTAMP,
        "DATAVENCIMENTO" TIMESTAMP,
        "VALORONS" NUMBER(18,2),
        "VALORFATURA" NUMBER(18,2),
        "ISFATURAAGRUPADA" CHAR(1),
        "NUMERONOTAFISCAL" VARCHAR2(20),
        "QTDARQUIVOSXML" NUMBER,
        "QTDARQUIVOSDANFE" NUMBER,
        "QTDARQUIVOSBOLETO" NUMBER,
        "QTDARQUIVOSFATURA" NUMBER,
        "QTDNOTASFISCAIS" NUMBER,
        "QTDBOLETOS" NUMBER,
        "QTDTITULOSCONTASPAGAR" NUMBER,
        "VALORTOTALNOTASFISCAIS" NUMBER(18,2),
        "VALORTOTALBOLETOS" NUMBER(18,2),
        "TIPOSITUACAOFATURATRANSMISSAO" VARCHAR2(30),
        "TIPOINTEGRACAOERP" VARCHAR2(30),
        "CODIGOTIPODOBRANCA" VARCHAR2(10),
        "CODIGOTIPOPAGAMENTO" VARCHAR2(10),
        "CODIGOFORNECEDORCONTACORRENTE" VARCHAR2(30),
        CONSTRAINT "RSM_TUSTIMPAUTDOCUMENTO_PK" PRIMARY KEY ("ID_IMPAUTDOCUMENTO")
);

   CREATE SEQUENCE "SEQ_RSM_TUSTIMPAUTDOCUMENTO" NOCACHE NOORDER NOCYCLE;
   

-- Armazena dados das transmissoras de energia
  CREATE TABLE "RSM_TUSTTRANSMISSORA" (
        "ID_TRANSMISSORA" NUMBER NOT NULL,
        -- Campos de <Transmissora>
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "USUARIOALTERACAO" VARCHAR2(30),
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "CODIGOONS" VARCHAR2(10),
        "NOME" VARCHAR2(100),
        "IDENTIFICADORPROCESSOIMPORTACAO" NUMBER,
        "FORMAPAGAMENTO" VARCHAR2(30),
        "ISEMITENOTAFISCAL" CHAR(1),
        "ISPOSSUIIMPOSTORETIDO" CHAR(1),
        "CODIGOFORNECEDOR" VARCHAR2(20),
        "CODIGOTIPODOBRANCA" VARCHAR2(10),
        "CODIGOTIPOPAGAMENTO" VARCHAR2(10),
        "CODIGOFORNECEDORCONTACORRENTE" VARCHAR2(10),
        -- Campos de <TransmissoraCadastroONS>
        "CNPJ" VARCHAR2(20),
        "RAZAOSOCIAL" VARCHAR2(100),
        "INSCRICAOESTADUAL" VARCHAR2(30),
        "CLASSIFICACAOEMPRESA" VARCHAR2(20),
        "REGIAO" VARCHAR2(20),
        "NOMEBANCO" VARCHAR2(50),
        "NUMEROBANCO" VARCHAR2(10),
        "AGENCIA" VARCHAR2(10),
        "CONTA" VARCHAR2(20),
        "FORMAENCAMINHAMENTOFATURAS" VARCHAR2(30),
        "URLSITE" VARCHAR2(200),
        "PERCENTUALALIQUOTAPISCOFINS" NUMBER(10,2),
        "CODIGOCONCESSAO" VARCHAR2(20),
        "DATACONCESSAO" TIMESTAMP,
        "CODIGOCONTRATO" VARCHAR2(30),
        "DATAINICIOCONTABIL" TIMESTAMP,
        "DATAINICIOOPERACAO" TIMESTAMP,
        -- Endereço
        "ENDERECO_CEP" VARCHAR2(10),
        "ENDERECO_LOGRADOURO" VARCHAR2(100),
        "ENDERECO_NUMERO" VARCHAR2(20),
        "ENDERECO_COMPLEMENTO" VARCHAR2(100),
        "ENDERECO_BAIRRO" VARCHAR2(50),
        "ENDERECO_CIDADE" VARCHAR2(50),
        "ENDERECO_ESTADO" VARCHAR2(2),
        CONSTRAINT "RSM_TUSTTRANSMISSORA_PK" PRIMARY KEY ("ID_TRANSMISSORA")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTTRANSMISSORA" NOCACHE NOORDER NOCYCLE;


-- Armazena empresas participantes do processo TUST
  CREATE TABLE "RSM_TUSTEMPRESA" (
        "ID_EMPRESATUST" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "USUARIOINCLUSAO" VARCHAR2(30),
        "DATAALTERACAO" TIMESTAMP,
        "USUARIOALTERACAO" VARCHAR2(30),
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "CODIGOEMPRESA" VARCHAR2(10),
        "CODIGOGRUPOPAGAMENTO" VARCHAR2(20),
        "CODIGOCENTROCUSTO" VARCHAR2(20),
        "CODIGOPROJETOCONTABIL" VARCHAR2(20),
        CONSTRAINT "RSM_TUSTEMPRESA_PK" PRIMARY KEY ("ID_EMPRESATUST")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTEMPRESA" NOCACHE NOORDER NOCYCLE;


-- Armazena filiais das empresas TUST
  CREATE TABLE "RSM_TUSTEMPRESAFILIAL" (
        "ID_EMPRESAFILIALTUST" NUMBER NOT NULL,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADOREMPRESATUST" NUMBER,
        "CODIGOFILIAL" VARCHAR2(10),
        "CODIGOONS" VARCHAR2(10),
        CONSTRAINT "RSM_TUSTEMPRESAFILIAL_PK" PRIMARY KEY ("ID_EMPRESAFILIALTUST")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTEMPRESAFILIAL" NOCACHE NOORDER NOCYCLE;
   

-- Armazena avisos de débito emitidos
  CREATE TABLE "RSM_TUSTAVISODEBITO" 
   (	"ID_AVISODEBITO" NUMBER NOT NULL, 
        "IDENTIFICADOR" NUMBER,
        "CODIGOEMPRESA" VARCHAR2(10),
        "CODIGOFILIAL" VARCHAR2(10),
        "CODIGOONS" VARCHAR2(10),
        "NOMEEMPRESA" VARCHAR2(100),
        "NUMEROAVD" VARCHAR2(20),
        "DATACOMPETENCIA" TIMESTAMP,
        "DATAVENCIMENTOPARCELA1" TIMESTAMP,
        "DATAVENCIMENTOPARCELA2" TIMESTAMP,
        "DATAVENCIMENTOPARCELA3" TIMESTAMP,
        CONSTRAINT "RSM_TUSTAVISODEBITO_PK" PRIMARY KEY ("ID_AVISODEBITO")
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTAVISODEBITO" NOCACHE NOORDER NOCYCLE;

-- Armazena itens dos avisos de débito
  CREATE TABLE "RSM_TUSTAVISODEBITOITEM" (
        "ID_AVISODEBITOITEM" NUMBER NOT NULL,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORAVISODEBITOTRANSMISSAO" NUMBER,
        "CODIGOONS" VARCHAR2(10),
        "NOMETRANSMISSORA" VARCHAR2(100),
        "CNPJTRANSMISSORA" VARCHAR2(20),
        "PERCENTUALREDEBASICA" NUMBER(10,2),
        "VALORREDEBASICA" NUMBER(18,2),
        "VALORPARCELA1" NUMBER(18,2),
        "VALORPARCELA2" NUMBER(18,2),
        "VALORPARCELA3" NUMBER(18,2),
        "VALORTOTAL" NUMBER(18,2),
        CONSTRAINT "RSM_TUSTAVISODEBITOITEM_PK" PRIMARY KEY ("ID_AVISODEBITOITEM")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTAVISODEBITOITEM" NOCACHE NOORDER NOCYCLE;

   
-- Armazena faturas de transmissão de energia
  CREATE TABLE "RSM_TUSTFATURATRANSMISSAO" (
        "ID_FATURATRANSMISSAO" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORAVISODEBITOTRANSMISSAO" NUMBER,
        "IDENTIFICADORAVISODEBITOTRANSMISSAOITEM" NUMBER,
        "IDENTIFICADORTRANSMISSORA" NUMBER,
        "IDENTIFICADORFATURATRANSMISSAOPAI" NUMBER,
        "FORMAPAGAMENTO" VARCHAR2(30),
        "CODIGOTRANSMISSORAONS" VARCHAR2(10),
        "CODIGOEMPRESAONS" VARCHAR2(10),
        "CODIGOEMPRESA" VARCHAR2(10),
        "CODIGOFILIAL" VARCHAR2(10),
        "DATACOMPETENCIA" TIMESTAMP,
        "DATAFATURA" TIMESTAMP,
        "DATAVENCIMENTO" TIMESTAMP,
        "VALORONS" NUMBER(18,2),
        "VALORFATURA" NUMBER(18,2),
        "ISFATURAAGRUPADA" CHAR(1),
        "NUMERONOTAFISCAL" VARCHAR2(20),
        "QTDARQUIVOSXML" NUMBER,
        "QTDARQUIVOSDANFE" NUMBER,
        "QTDARQUIVOSBOLETO" NUMBER,
        "QTDARQUIVOSFATURA" NUMBER,
        "QTDNOTASFISCAIS" NUMBER,
        "QTDBOLETOS" NUMBER,
        "QTDTITULOSCONTASPAGAR" NUMBER,
        "VALORTOTALNOTASFISCAIS" NUMBER(18,2),
        "VALORTOTALBOLETOS" NUMBER(18,2),
        "TIPOSITUACAOFATURATRANSMISSAO" VARCHAR2(30),
        "TIPOINTEGRACAOERP" VARCHAR2(30),
        "CODIGOTIPODOBRANCA" VARCHAR2(10),
        "CODIGOTIPOPAGAMENTO" VARCHAR2(10),
        "CODIGOFORNECEDORCONTACORRENTE" VARCHAR2(10),
        CONSTRAINT "RSM_TUSTFATURATRANSMISSAO_PK" PRIMARY KEY ("ID_FATURATRANSMISSAO")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTFATURATRANSMISSAO" NOCACHE NOORDER NOCYCLE;


-- Armazena arquivos vinculados à fatura de transmissão
  CREATE TABLE "RSM_TUSTFATTRANSMISSAOARQUIVO" (
        "ID_FATURATRANSMISSAOARQUIVO" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "ID_FATURATRANSMISSAO" NUMBER,
        "ID_ARQUIVO" VARCHAR2(50),
        "TP_ARQUIVO" VARCHAR2(20),
        "NOMEARQUIVO" VARCHAR2(100),
        "ISCANCELADO" CHAR(1),
        "DATACANCELAMENTO" TIMESTAMP,
        CONSTRAINT "RSM_TUSTFATTRANSMISSAOARQ_PK" PRIMARY KEY ("ID_FATURATRANSMISSAOARQUIVO")
);
   
   CREATE SEQUENCE "SEQ_RSM_TUSTFATTRANSMISSAOARQ" NOCACHE NOORDER NOCYCLE;


-- Armazena boletos vinculados à fatura de transmissão
  CREATE TABLE "RSM_TUSTFATTRANSMISSAOBOLETO" (
        "ID_FATURATRANSMISSAOBOLETO" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "CNPJ_BENEFICIARIO" VARCHAR2(20),
        "CNPJ_PAGADOR" VARCHAR2(20),
        "DATADOCUMENTO" TIMESTAMP,
        "DATAVENCIMENTO" TIMESTAMP,
        "VALORTOTAL" NUMBER(18,2),
        "LINHADIGITAVEL" VARCHAR2(60),
        "ISCANCELADO" CHAR(1),
        "DATACANCELAMENTO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORFATURATRANSMISSAO" NUMBER,
        "IDENTIFICADORARQUIVO" VARCHAR2(50),
        CONSTRAINT "RSM_TUSTFATTRANSMISSAOBLT_PK" PRIMARY KEY ("ID_FATURATRANSMISSAOBOLETO")
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTFATTRANSMISSAOBLT" NOCACHE NOORDER NOCYCLE;


-- Armazena notas fiscais vinculadas à fatura de transmissão
  CREATE TABLE "RSM_TUSTFATTRANSMISSAONF" (
        "ID_FATURATRANSMISSAONF" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORFATURATRANSMISSAO" NUMBER,
        "IDENTIFICADORARQUIVO" VARCHAR2(50),
        "CNPJ_EMISSOR" VARCHAR2(20),
        "NOME_EMISSOR" VARCHAR2(100),
        "CNPJ_DESTINATARIO" VARCHAR2(20),
        "NOME_DESTINATARIO" VARCHAR2(100),
        "NUMERONOTAFISCAL" VARCHAR2(20),
        "NUMEROFATURA" VARCHAR2(20),
        "DATAEMISSAO" TIMESTAMP,
        "DATAVENCIMENTO" TIMESTAMP,
        "VALORTOTAL" NUMBER(18,2),
        "CHAVENFE" VARCHAR2(50),
        "ISCANCELADO" CHAR(1),
        "DATACANCELAMENTO" TIMESTAMP,
        CONSTRAINT "RSM_TUSTFATTRANSMISSAONF_PK" PRIMARY KEY ("ID_FATURATRANSMISSAONF")
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTFATTRANSMISSAONF" NOCACHE NOORDER NOCYCLE;


-- Armazena títulos de contas a pagar vinculados à fatura de transmissão
  CREATE TABLE "RSM_TUSTFATTRANSMISSAOTITCP" (
        "ID_FATURATRANSMISSAOTITCP" NUMBER NOT NULL,
        "DATAINCLUSAO" TIMESTAMP,
        "DATAALTERACAO" TIMESTAMP,
        "INATIVO" CHAR(1),
        "EXCLUIDO" CHAR(1),
        "DATAEXCLUSAO" TIMESTAMP,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORFATURATRANSMISSAO" NUMBER,
        "SEQUENCIAL" NUMBER,
        "CODIGOFORNECEDOR" VARCHAR2(20),
        "NUMEROTITULO" VARCHAR2(50),
        "CODIGOEMPRESA" VARCHAR2(10),
        "CODIGOFILIAL" VARCHAR2(10),
        "CODIGOTIPOTITULO" VARCHAR2(10),
        "DATAEMISSAO" TIMESTAMP,
        "DATAENTRADA" TIMESTAMP,
        "DATAVENCIMENTO" TIMESTAMP,
        "DATAPROGRAMACAOPAGAMENTO" TIMESTAMP,
        "DATACOMPETENCIA" TIMESTAMP,
        "VALORTITULO" NUMBER(18,2),
        "VALORCORRIGIDO" NUMBER(18,2),
        "CODIGOMOEDA" VARCHAR2(5),
        "CODIGOTIPOCOBRANCA" VARCHAR2(10),
        "CODIGOTIPOPAGAMENTO" VARCHAR2(10),
        "CODIGOSISTEMA" VARCHAR2(10),
        "IDPORTADOR" VARCHAR2(50),
        "CODIGOGRUPOPAGAMENTO" VARCHAR2(20),
        "CODIGOCENTROCUSTO" VARCHAR2(20),
        "CODIGOPROJETO" VARCHAR2(30),
        "ISCANCELADO" CHAR(1),
        "DATACANCELAMENTO" TIMESTAMP,
        CONSTRAINT "RSM_TUSTFATTRANSMISSAOTITCP_PK" PRIMARY KEY ("ID_FATURATRANSMISSAOTITCP")
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTFATTRANSTITCP" NOCACHE NOORDER NOCYCLE;


-- Armazena anexos diversos relacionados ao processo TUST
  CREATE TABLE "RSM_TUSTANEXO" (
        "ID_ANEXO" NUMBER NOT NULL,
        "IDENTIFICADOR" NUMBER,
        "IDENTIFICADORARQUIVO" VARCHAR2(50),
        "MODEL" VARCHAR2(50),
        "FOREIGNKEY" NUMBER,
        "FILENAME" VARCHAR2(200),
        "SIZE" NUMBER,
        CONSTRAINT "RSM_TUSTANEXO_PK" PRIMARY KEY ("ID_ANEXO")
   );
   
   CREATE SEQUENCE "SEQ_RSM_TUSTANEXO" NOCACHE NOORDER NOCYCLE;


CREATE OR REPLACE TYPE RSM_TYPEROW IS TABLE OF VARCHAR2 (100);


CREATE OR REPLACE FUNCTION RSM_GETIN(strlist VARCHAR2)
   RETURN RSM_TYPEROW
   PIPELINED IS
   ROW_STR RSM_TYPEROW;
   
BEGIN
   FOR r_row IN (SELECT trim(regexp_substr(strlist, '[^,]+', 1, LEVEL)) AS STR FROM DUAL
                 CONNECT BY instr(strlist, ',', 1, LEVEL - 1) > 0)
    LOOP
       PIPE ROW(r_row.STR);
    END LOOP;
END;
/